extends: stylelint-config-standard
ignoreFiles:
  - node_modules/**/*
  - boac/static/lib
plugins:
  - stylelint-scss
  - stylelint-order
rules:
  block-no-empty: true
  color-hex-case: lower
  color-no-invalid-hex: true
  comment-empty-line-before: always
  comment-no-empty: true
  comment-whitespace-inside: always
  declaration-block-no-redundant-longhand-properties: true
  declaration-block-no-shorthand-property-overrides: true
  font-family-name-quotes: always-where-recommended
  font-family-no-duplicate-names: true
  function-comma-space-after: always
  function-name-case: lower
  function-url-quotes: never
  function-whitespace-after: always
  indentation: 2
  # https://github.com/sasstools/sass-lint/blob/develop/lib/config/property-sort-orders/smacss.yml
  order/properties-order:
    - display
    - position
    - top
    - right
    - bottom
    - left
  length-zero-no-unit: true
  max-empty-lines: 1
  max-line-length: 120
  media-feature-name-no-unknown: true
  media-feature-name-no-vendor-prefix: true
  no-descending-specificity: true
  no-duplicate-at-import-rules: true
  no-duplicate-selectors: true
  no-empty-source: true
  no-eol-whitespace: true
  no-extra-semicolons: true
  no-invalid-double-slash-comments: true
  no-missing-end-of-source-newline: always
  property-case: lower
  property-no-unknown: true
  selector-attribute-quotes: always
  selector-type-no-unknown: null
  shorthand-property-no-redundant-values: null
  string-no-newline: true
  string-quotes: double
  unit-case: lower
  unit-no-unknown: true
  value-keyword-case: lower
  value-no-vendor-prefix: true
