sudo: required
language: python
python: "3.6"

addons:
  postgresql: "9.5"

before_install:
  - cd ${TRAVIS_BUILD_DIR}

  # Set up test db
  - psql -c 'create database boac_test;' -U postgres
  - psql boac_test -c 'create extension pg_trgm;' -U postgres
  - psql boac_test -c 'create role boac superuser login; alter schema public owner to boac;' -U postgres

install:
  - pip3 install -r requirements.txt
  - pip3 install tox

script:
  - tox
