version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
      python: 3.8
    commands:
      - npm -v
      - npm install

  pre_build:
    commands:
      - echo "pre_build phase"

  build:
    commands:
      - node -v
      - nvm use
      - npm run build-vue

  post_build:
    commands:
      - chmod 755 ./scripts/*.sh
      - ./scripts/create-build-summary.sh

artifacts:
  files:
  - '.ebextensions/**/*'
  - 'app/**/*'
  - 'boac/**/*'
  - 'config/**/*'
  - 'dist/**/*'
  - 'fixtures/**/*'
  - 'requirements.txt'
  - 'run.py'
  - 'scripts/**/*'
