version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
      python: 3.8

  build:
    commands:
      - npm install
      - npm run build-vue

  post_build:
    commands:
      - chmod 755 ./scripts/*.sh
      - ./scripts/create-build-summary.sh

artifacts:
  files:
  - '.ebextensions/**/*'
  - 'app/**/*'
  - 'boac/**/*'
  - 'config/**/*'
  - 'dist/**/*'
  - 'fixtures/**/*'
  - 'requirements.txt'
  - 'run.py'
  - 'scripts/**/*'
