version: 0.2

eb_codebuild_settings:
  CodeBuildServiceRole: arn:aws:iam::697877139013:role/service-role/code-build-BOAC-service-role
  ComputeType: BUILD_GENERAL1_MEDIUM
  Image: aws/codebuild/nodejs:6.3.1
  Timeout: 60

phases:
  install:
    commands:
      - npm -v
      - npm install
      - npm install -g bower
      - npm install -g gulp

  pre_build:
    commands:
      - echo "pre_build phase"

  build:
    commands:
      - sudo ./node_modules/.bin/bower install --allow-root
      - sudo ./node_modules/.bin/gulp dist --allow-root

  post_build:
    commands:
      - chmod 755 ./scripts/*.sh
      - ./scripts/create-build-summary.sh

artifacts:
  files:
  - '.ebextensions/**/*'
  - 'app/**/*'
  - 'boac/**/*'
  - 'config/**/*'
  - 'dist/**/*'
  - 'fixtures/**/*'
  - 'requirements.txt'
  - 'run.py'
  - 'scripts/**/*'
